### ISSUE TITLE
Problem about how to show the policy being executed in the GridWorld?

### ISSUE THREAD

**Issue by hychong1997** [grockious/lcrl#1]
Execuse me , can you tell me how to show the policy being executed in the environment like the matlab version (http://www.cs.ox.ac.uk/conferences/LCRL/)?
Your reply is highly appreciated!

**Comment by grockious** [comment]
Thanks for the comment. I haven't implemented a plotter/animator yet, but it will be included in the next update of the repo!

**Comment by hychong1997** [comment]
Thank you very much.

**Comment by grockious** [comment]
Dear @hychong1997,

The animator is added to the repo. Please let me know if you run into an issue, otherwise I am going to close this as solved. 

Cheers!

**Comment by hychong1997** [comment]
Dear&nbsp;Hosein Hasanbeig,
Thank you very much!



---Original---
